### PR TITLE
Add support for VobSub in MKV files

### PR DESCRIPTION
**Pull request by ecdye**
This will add support for decoding a VobSub subtitle stream directly
from an input Matroska file. This eliminates the need for a user to
create an intermediate file before using macSubtitleOCR

### CODE REVIEW

**Comment by ecdye** [comment]
@timj, Here is a really nice one. I originally did this to prepare for processing VobSub streams from the MKV files but this change alone seems to improve decoding performance by a *lot*, in fact it might even be faster than ffmpeg. Let me know how it works for you.

**Comment by timj** [comment]
I'm using `main` at the moment and it seems very slow but that's probably because I don't know how to make `swift build` give me the fast binary.  It's not using any cores at all even if I ramp it up.

I see that the ffmpeg went away. I will look at the invert colors option.

**Comment by ecdye** [comment]
Actually FFmpeg is still default, the internal decoder option in just hidden in the help. You can see it by using `--help-hidden`

As for the compiling with optimizations try running `swift build --configuration release`

**Comment by ecdye** [comment]
So, because of the way the vision API works, you can really only do a max of 5-6 threads. Otherwise it seems to hang like that. I should probably add a cap, or something. I found only one reference to this in one of Apple's developer videos, but they seemed to indicate that it is because of the large amount of memory that the Machine Learning Vision API uses.

**Comment by timj** [comment]
Not trying to specify cores helped and it does finish. It's kind of odd since I never see any load on the machine when I run this. RAM isn't an issue on this computer and it wasn't using any when I killed it.

**Comment by timj** [comment]
So for me the sweet spot is 2 cores:

```
$ time macSubtitleOCR -t 1 x.idx .
macSubtitleOCR -t 1 x.idx .  69.09s user 13.25s system 191% cpu 42.891 total
$ time macSubtitleOCR -t 2 x.idx .
macSubtitleOCR -t 2 x.idx .  57.40s user 13.00s system 221% cpu 31.850 total
$ time macSubtitleOCR -t 5 x.idx . 
macSubtitleOCR -t 5 x.idx .  55.68s user 10.77s system 211% cpu 31.379 total
$ time macSubtitleOCR -t 10 x.idx .
macSubtitleOCR -t 10 x.idx .  56.49s user 8.60s system 206% cpu 31.466 total
$ time macSubtitleOCR -t 15 x.idx .
macSubtitleOCR -t 15 x.idx .  57.82s user 7.59s system 208% cpu 31.334 total
$ time macSubtitleOCR -t 18 x.idx .
macSubtitleOCR -t 18 x.idx .  84.33s user 4.02s system 215% cpu 40.986 total
$ time macSubtitleOCR -t 20 x.idx .
<hangs without using any CPU> ^C
macSubtitleOCR -t 20 x.idx .  0.46s user 0.16s system 0% cpu 4:51.30 total
```

There are 20 cores. It doesn't use any GPU. I had assumed that the Vision API was going to use the neural engine or GPU.
With 19 threads it seems to be using 100% CPU forever but after 15 minutes didn't complete.

**Comment by ecdye** [comment]
> So for me the sweet spot is 2 cores:
> 
> ```
> $ time macSubtitleOCR -t 1 x.idx .
> macSubtitleOCR -t 1 x.idx .  69.09s user 13.25s system 191% cpu 42.891 total
> $ time macSubtitleOCR -t 2 x.idx .
> macSubtitleOCR -t 2 x.idx .  57.40s user 13.00s system 221% cpu 31.850 total
> $ time macSubtitleOCR -t 5 x.idx . 
> macSubtitleOCR -t 5 x.idx .  55.68s user 10.77s system 211% cpu 31.379 total
> $ time macSubtitleOCR -t 10 x.idx .
> macSubtitleOCR -t 10 x.idx .  56.49s user 8.60s system 206% cpu 31.466 total
> $ time macSubtitleOCR -t 15 x.idx .
> macSubtitleOCR -t 15 x.idx .  57.82s user 7.59s system 208% cpu 31.334 total
> $ time macSubtitleOCR -t 18 x.idx .
> macSubtitleOCR -t 18 x.idx .  84.33s user 4.02s system 215% cpu 40.986 total
> $ time macSubtitleOCR -t 20 x.idx .
> <hangs without using any CPU> ^C
> macSubtitleOCR -t 20 x.idx .  0.46s user 0.16s system 0% cpu 4:51.30 total
> ```
> 
> There are 20 cores. It doesn't use any GPU. I had assumed that the Vision API was going to use the neural engine or GPU. With 19 threads it seems to be using 100% CPU forever but after 15 minutes didn't complete.

Yeah, thats where I'm confused as well. On my MacBook Pro M3 it seems to utilize 5 cores pretty well, but if I do more it will hang forever. I suspect it's more of an issue with the API than anything, but can't say for sure. It seems to only use a minimal amount of the GPU for me as well. I'm not really sure why, but I'll just attribute it to the black magic of Apple's API.

**Comment by ecdye** [comment]
> Thanks for this. I just tried it on an MKV and it crashes for me.

I was afraid of that, I only had one test case on hand to throw at it so I wasn't sure if I had really caught all the edge cases. 


> Quick question, when you extract from an MKV do you use the subtitle language from the MKV as the language hint or does it always use the `--language` parameter?

Currently no I'm actually only using the language parameter, that's a good suggestion. I should be able to add that pretty easily.

**Comment by timj** [comment]
Actually I'm getting crashes with .idx files on main.

**Comment by ecdye** [comment]
> Actually I'm getting crashes with .idx files on main.

So just when you try to pass a `.idx` file in as the file to process? Or that in addition to when passing in a mkv with a VobSub stream?

**Comment by timj** [comment]
Yes.

```
$ macSubtitleOCR --save-images B1_t05.sub .
zsh: trace trap  macSubtitleOCR --save-images B1_t05.sub .
```

[crash.tgz](https://github.com/user-attachments/files/17470157/crash.tgz)

**Comment by ecdye** [comment]
> Yes.
> 
> ```
> $ macSubtitleOCR --save-images B1_t05.sub .
> zsh: trace trap  macSubtitleOCR --save-images B1_t05.sub .
> ```
> 
> [crash.tgz](https://github.com/user-attachments/files/17470157/crash.tgz)

OK, I think I fixed it. It seems like it has something to do with a technically malformed file according to specification, but I'm not sure because I also might be parsing slightly wrong. At least I seemed to be able to fix it. Let me know if you notice any Errors

**Comment by timj** [comment]
Thanks. I will try it again. This did work before (and works fine with ffmpeg decoder) but I can't remember whether I ever tried it with internal decoder.

**Comment by ecdye** [comment]
Interesting, I'll double check, but I'm guessing you just never tried with internal

**Pull request merged**
