### PR TITLE
Add initial support for VobSub subtitles

### PR DESCRIPTION
**Pull request by ecdye**
This will only add support for VobSub stream decoding for the moment.
In the future additional support will be implemented for extracting the
stream from an input `.mkv` file like has been done with PGS subtitle
streams already.

For now this focuses on simply adding functionality for the basic VobSub
format without any extra bells or whistles.

### CODE REVIEW

**Comment by ecdye** [comment]
@timj If you don't mind, before I merge, would you try running this on a handful of you VobSub subtitle format files. This PR won't support reading them from Matroska files, but I will add that in a future PR. I just want to see how accurate this is for more than just the handful of files I have thrown at it.

**Comment by timj** [comment]
I will be happy to take a look this evening.

**Comment by timj** [comment]
First attempt:
```
$ macSubtitleOCR subs.idx . 
macSubtitleOCR/VobSubParser.swift:134: Fatal error: Unexpectedly found nil while unwrapping an Optional value
zsh: trace trap  macSubtitleOCR subs.idx .
```
with [subs.tar.gz](https://github.com/user-attachments/files/17246728/subs.tar.gz)

**Comment by ecdye** [comment]
Whelp, this is why I'm glad I waited to merge. I'll try to look into this again this evening and see if I can figure out what I need to do to fix it.

**Comment by ecdye** [comment]
Alright, I think I fixed that file at the very least, give it a try now @timj. I do have to say, I appreciate your taste in movies based off of that subtitle file.

**Comment by ecdye** [comment]
> Thanks. That works for me. Much better quality than I get out of Subtools with Tesseract so that's a bonus. I can try some more examples over the weekend.

Glad to hear it! That's actually what drew me to want to do this originally, the fact that the macOS OCR API seems to be really good.

**Pull request merged**
