### PR TITLE
Fix leftover issues with internal VobSub decoder

### LINKED ISSUE #18: VobSub Timestamp Inconsistencies
Thank you for making such great progress. I tried a couple more VOBSUB files as promised. Attached are two different failures.

* "crash" is a simple crash. "macSubtitleOCR/VobSubParser.swift:208: Fatal error: Unexpectedly found nil while unwrapping an Optional value"
* "time" is more interesting in that the end timestamps are wrong.

```
18
00:01:12,739 --> 00:08:04,716
I was just a kid, 26 years old.

19
00:01:16,643 --> 00:08:08,620
Anyway...

20
00:01:19,513 --> 00:08:11,490
they were building the lower level
of the George Washington Bridge...
```

It looks like the start timestamps are correct. SubTools does generate correct end timestamps.

[bad.tar.gz](https://github.com/user-attachments/files/17265248/bad.tar.gz)

### LINKED ISSUE #21: VobSub Interlacing Inconsistencies
Trying a different disk from #20 and whilst the image data looks close it seems there is a slight blurriness to it that is messing up the OCR.

eg

subtitle_11

with subtools looking like:

image

and VLC:

image

and the macSubtitleOCR subtitle comes out as:

```
11
00:00:47,719 --> 00:00:54,884
and Im crewing Welverhe slashing
piles with his adamantine claws.
```

vs SubTools with Tesseract:

```
and I'm drlwlng Wolverlne slashlng
prices with hls adamantlne claws.
```

That's a "good" example. Some other ones are much less usable. SubTools is much better though.

Here are the VOBSUB files:

[fuzz.tgz](https://github.com/user-attachments/files/17320035/fuzz.tgz)

### PR DESCRIPTION
**Pull request by ecdye**
This also adds additional tests to be run that will ensure both the
FFmpeg decoder works properly, as well as the internal decoder (at least
on the test files, better test files that test edge cases better would
probably be ideal).

Fixes #18
Fixes #21

Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by ecdye** [comment]
@timj Let me know if these combined fixes work for your library of files with the internal decoder.

**Comment by timj** [comment]
Fantastic. You've fixed the fuzziness problem in your decoder. Looks essentially identical to the ffmpeg variant.

This is great. The baffling issue now being that the OCR come out differently even though the images are effectively the same.

```
 11
-00:00:47,719 --> 00:00:50,705
-and Im drawing Wolverine slashing
-prices with his adamantine claws.
+00:00:47,719 --> 00:00:52,235
+and I'm drawing Wolverine slashing
+prices/with his adamantinerclaws.
```

The top one is the internal decoder and the bottom is ffmpeg. The top one is almost perfect but misses the apostrophe. The ffmpeg one is worse but does get the apostrophe...

**Comment by ecdye** [comment]
> The top one is the internal decoder and the bottom is ffmpeg. The top one is almost perfect but misses the apostrophe. The ffmpeg one is worse but does get the apostrophe...

I think the issue is actually due to FFmpeg doing a little bit of internal scaling of the image. I'm going to try and do some tuning for the image output, I think adding a little more buffer around the image, and also trying tom fine tune the OCR engine will help. 

Out of curiosity, you are using the `--language-correction` flag right?

**Comment by timj** [comment]
> I think adding a little more buffer around the image

The buffer is almost the same. 499x75 for internal and 497x73 for ffmpeg in the Wolverine example.


> Out of curiosity, you are using the --language-correction flag right?

Yes. (I am wondering if this should be the default -- the OCR engine is fast already so I'm not sure why you would ever really want the even faster but less accurate version).

**Comment by ecdye** [comment]
> > I think adding a little more buffer around the image
> 
> The buffer is almost the same. 499x75 for internal and 497x73 for ffmpeg in the Wolverine example.

Yeah, it is interesting, hopefully I'll be able to fine tune it, and I'm also hoping to make it so that you can optionally build with FFmpeg support but not require it as that would be super nice.

> > Out of curiosity, you are using the --language-correction flag right?
> 
> Yes. (I am wondering if this should be the default -- the OCR engine is fast already so I'm not sure why you would ever really want the even faster but less accurate version).

This is a fair point, one that I have also considered. I tend to agree with you, I think I'll probably make it default and simply include an option to disable it (mostly because why not).

**Comment by timj** [comment]
I've tested a few more discs and included other languages. Sometimes everything is perfect and other times there are problems with the OCR. On the plus side none of my files crashed anything.

**Comment by ecdye** [comment]
Do the problems with the OCR seem to be related to the image output? I think sometimes its just an issue with the words in the subtitles being too close together, but I'm still trying to see if I can refine it, with only a little success.

**Comment by timj** [comment]
The problem is that asking Apple to do the extraction via selection and copy and paste from the image it always gets it right (or at least I've not seen it go wrong).

eg 
Screenshot 2024-10-14 at 20 32 42

extracts as 

> It's a joke.
> If you're gonna be an Arsenal fan,

but the OCR from the subtitle is:

> It's ajoke.
> If you're gonna be an Arsenal fan,

Which is close but strangely wrong given what we imagine "--language-correction" is meant to be doing (surely it would work out that "ajoke" is not a word).


In a different one OCR for

subtitle_45

gives:

> You are about ito experience the mystery
> whichreaches from theinner mindl

but Apple preview gives me:

> You are about to experience the mystery which reaches from the inner mind.

without language correction I get:

> You are about ito experience the mystery
> whichreaches from theinner mindl

(which is the same but that's by chance since it is clear that the language correction is worse).

Or this one:

subtitle_10

> whic hihe uses to a destructive
> andantisociallendl

vs Apple Preview:

> which he uses to a destructive and antisocial end.

So a lot of the issues are word breaks but what are Apple doing differently?

**Comment by timj** [comment]
PS I tried `--fast-mode` and get no text at all in the SRT files (just the timestamps).

**Comment by timj** [comment]
Just thought to look at the JSON and for that last one it's

```json
  {
    "image": 10,
    "lines": [
      {
        "confidence": 1,
        "height": 27,
        "text": "whic hihe uses to a destructive",
        "width": 366,
        "x": 0,
        "y": 0
      },
      {
        "confidence": 0.5,
        "height": 21,
        "text": "andantisociallendl",
        "width": 230,
        "x": 70,
        "y": 39
      }
    ],
    "text": "whic hihe uses to a destructive\nandantisociallendl"
  },
```
which is reporting less confidence in the second line.

**Comment by timj** [comment]
Apple Preview also seems to select the text as a single entity rather than treating them as separate lines. It says the bounding box is 368x63.

230x21 for the second line does seem to be very tight. A height of 27 does seem to be better. (Preview reports the width as 368).

Screenshot 2024-10-14 at 21 31 25

**Comment by timj** [comment]
These are with ffmpeg. With the internal decoder it's better:

```json
  {
    "image": 10,
    "lines": [
      {
        "confidence": 1,
        "height": 202,
        "text": "which he uses to a destructive",
        "width": 716,
        "x": 0,
        "y": 0
      },
      {
        "confidence": 1,
        "height": 173,
        "text": "and antisocial end.",
        "width": 447,
        "x": 136,
        "y": 289
      }
    ],
    "text": "which he uses to a destructive\nand antisocial end."
  },
```
The images only differ by 2 pixels (370x65) so I'm not sure why the coordinates in the JSON file are so wildly different (and not related to the image dimensions at all it seems.

**Comment by timj** [comment]
I am starting to think that a couple of extra pixels around the ffmpeg image might help.

**Comment by ecdye** [comment]
Yeah, I'm also thinking that I may make the internal decoder default again too, since as hacked together as it is, it still seems to be more accurate in most cases than ffmpeg.

**Comment by ecdye** [comment]
Yeah, I don't want to nix it in general, but I want to try and make it optional so it can also be compiled completely independently.

I'm definitely going to try and add some padding and see if that helps, although I think in theory it should be adding the padding to all images IIRC, but I'll look at it some more.

**Comment by timj** [comment]
Thanks. The padding improved the ffmpeg OCR. Now internal and ffmpeg make different mistakes with one not being obviously better than the other. In most cases if one is wrong the other is better and hopefully that will give you a clue. Not sure if more padding would make things better to both.

The reported coordinates in the JSON file for internal are unrelated to the size of the saved image. The coordinates for the ffmpeg decoder are more consistent with the subtitle I used as an example above (each line has the same height now).

**Pull request merged**
